In [1]:
import numpy as np

import pandas as pd

import tensorflow as tf 

import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv('MiningProcess_Flotation_Plant_Database_hour.csv')
df.set_index('date', inplace=True)

In [3]:
df.head()

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.2,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,66.91,1.31
2017-03-10 02:00:00,55.2,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,67.06,1.11
2017-03-10 03:00:00,55.2,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,66.97,1.27
2017-03-10 04:00:00,55.2,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,66.75,1.36
2017-03-10 05:00:00,55.2,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,66.63,1.34

In [4]:

df = df.drop(['% Iron Concentrate'], axis=1)

In [5]:
Y = df['% Silica Concentrate']
X = df.drop(['% Silica Concentrate'], axis=1)

In [7]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scaled = pd.DataFrame(min_max_scaler.fit_transform(X), columns=X.columns)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [9]:
df.head()

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 06 Air Flow,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.2,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,251.232529,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,1.31
2017-03-10 02:00:00,55.2,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.909494,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,1.11
2017-03-10 03:00:00,55.2,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.242161,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,1.27
2017-03-10 04:00:00,55.2,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,249.825122,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,1.36
2017-03-10 05:00:00,55.2,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.249600,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,1.34

In [10]:

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 
from math import sqrt  


n_features = X_train.shape[1]

# define model
model = Sequential()
model.add(Dense(21,activation='relu', kernel_initializer='he_normal', input_shape=(n_features,)))
model.add(Dense(8,activation='relu',  kernel_initializer='he_normal'))
model.add(Dense(1))

# compile the model
model.compile(optimizer='adam', loss='mse')

In [11]:
model.fit(X_train, Y_train, epochs=100, batch_size=32, verbose=0)

In [12]:
error = model.evaluate(X_test, Y_test)
print('MSE: %.3f, RMSE: %.3f' % (error, sqrt(error)))

26/26 [==============================] - 0s 1ms/step - loss: 0.9988
MSE: 0.999, RMSE: 0.999

In [21]:
i = 1299
row = [df['% Iron Feed'].iloc[i],df['% Silica Feed'].iloc[i],df['Starch Flow'].iloc[i],df['Amina Flow'].iloc[i],df['Ore Pulp Flow'].iloc[i],df['Ore Pulp pH'].iloc[i],df['Ore Pulp Density'].iloc[i],df['Flotation Column 01 Air Flow'].iloc[i],df['Flotation Column 02 Air Flow'].iloc[i],df['Flotation Column 03 Air Flow'].iloc[i],df['Flotation Column 04 Air Flow'].iloc[i],df['Flotation Column 05 Air Flow'].iloc[i],df['Flotation Column 06 Air Flow'].iloc[i],df['Flotation Column 07 Air Flow'].iloc[i],df['Flotation Column 01 Level'].iloc[i],df['Flotation Column 02 Level'].iloc[i],df['Flotation Column 03 Level'].iloc[i],df['Flotation Column 04 Level'].iloc[i],df['Flotation Column 05 Level'].iloc[i],df['Flotation Column 06 Level'].iloc[i],df['Flotation Column 07 Level'].iloc[i]]
row = min_max_scaler.transform([row])
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

Predicted: 2.076

In [14]:
row

array([[0.92404514, 0.15425366, 0.36894935, 0.2484957 , 0.60251283,
        0.35247445, 0.37626442, 0.54345314, 0.54912706, 0.58012282,
        0.5332351 , 0.64311335, 0.655122  , 0.66071648, 0.47650069,
        0.46226229, 0.20308601, 0.37166914, 0.29685422, 0.29405443,
        0.34864874]])

In [15]:
yhatt = model.predict(X_test)
yhatt

array([[2.0759196],
       [2.967885 ],
       [3.6446025],
       [2.2260296],
       [1.8741397],
       [2.1376002],
       [1.7886626],
       [1.7651216],
       [2.147095 ],
       [2.3472815],
       [2.0403547],
       [1.8499949],
       [2.6878896],
       [2.3641732],
       [2.0819018],
       [4.1638327],
       [2.1500788],
       [3.7630608],
       [1.8839214],
       [2.6350121],
       [2.548835 ],
       [2.392887 ],
       [1.5366465],
       [2.4873827],
       [2.4100997],
       [1.6058466],
       [2.564437 ],
       [2.5311842],
       [2.1065245],
       [1.6939975],
       [2.8953032],
       [2.7234714],
       [1.7574321],
       [1.8474319],
       [2.9073555],
       [2.4697418],
       [2.7500587],
       [1.741431 ],
       [2.5564299],
       [2.3475115],
       [2.8535776],
       [2.7152798],
       [1.6538957],
       [2.615176 ],
       [2.4077907],
       [4.20986  ],
       [2.6004198],
       [2.1869097],
       [1.7755624],
       [2.353582 ],
       [2.3947845],
       [1.4797219],
       [2.0328596],
       [2.6594415],
       [1.652662 ],
       [1.8010527],
       [3.0296059],
       [1.6661972],
       [1.5976887],
       [2.239901 ],
       [4.660347 ],
       [1.5385573],
       [2.400398 ],
       [2.2972941],
       [4.046953 ],
       [2.403458 ],
       [1.8378596],
       [2.2093635],
       [1.7524987],
       [1.5956365],
       [2.2693884],
       [2.763562 ],
       [3.1757982],
       [2.0979319],
       [2.8557932],
       [2.2923439],
       [1.8484744],
       [1.984941 ],
       [2.2702405],
       [2.0843196],
       [2.5595677],
       [3.2673466],
       [2.1866717],
       [2.6677668],
       [2.376665 ],
       [1.787465 ],
       [3.0146716],
       [2.7616217],
       [1.8777485],
       [2.3254554],
       [1.7110654],
       [3.2804296],
       [3.2361724],
       [2.1262887],
       [3.217644 ],
       [2.8948348],
       [2.0984223],
       [1.7319615],
       [2.7893875],
       [3.1562712],
       [3.1370876],
       [2.7817075],
       [1.7296518],
       [3.4976537],
       [1.8167425],
       [3.4429467],
       [1.5292075],
       [2.7292492],
       [2.9012904],
       [2.1510081],
       [2.6760545],
       [2.5397007],
       [1.8687217],
       [3.062978 ],
       [2.3700373],
       [1.6986176],
       [3.295192 ],
       [2.043848 ],
       [2.2215447],
       [1.5410377],
       [2.40862  ],
       [2.7928784],
       [2.940208 ],
       [3.1302443],
       [2.3656633],
       [2.2162519],
       [1.6102649],
       [2.3160038],
       [2.3334846],
       [2.016415 ],
       [3.2013602],
       [2.1147602],
       [2.5098207],
       [1.7056825],
       [2.6556737],
       [1.8556628],
       [1.9989661],
       [2.1858022],
       [1.9485832],
       [2.047482 ],
       [1.8737837],
       [2.3843365],
       [2.8016913],
       [2.2426252],
       [1.7796801],
       [1.9484642],
       [1.8908156],
       [2.4772885],
       [1.7097467],
       [2.4029174],
       [1.7392571],
       [1.5537574],
       [2.1113663],
       [2.6482127],
       [2.3108523],
       [1.526483 ],
       [3.5582001],
       [2.7169425],
       [3.5902824],
       [1.7052205],
       [1.5692528],
       [1.684833 ],
       [2.7648427],
       [1.8077592],
       [2.824013 ],
       [1.5954605],
       [2.3773112],
       [2.549328 ],
       [1.8487202],
       [3.9160774],
       [2.4010642],
       [3.0753944],
       [3.059098 ],
       [1.943007 ],
       [1.6319234],
       [3.5995457],
       [2.6415226],
       [2.5692227],
       [2.6196506],
       [2.065505 ],
       [1.7426819],
       [3.010284 ],
       [1.7220064],
       [2.217406 ],
       [2.2760315],
       [3.8317254],
       [2.3417838],
       [3.8498175],
       [2.6165726],
       [2.4869206],
       [2.1191344],
       [2.2535474],
       [1.8665366],
       [1.5543443],
       [2.5088215],
       [2.9074452],
       [2.2135234],
       [2.5855713],
       [1.6023194],
       [1.606257 ],
       [3.4405236],
       [2.9926794],
       [2.1316514],
       [2.256118 ],
       [1.6095641],
       [2.3424907],
       [1.9338346],
       [2.0222983],
       [2.1131341],
       [2.4131517],
       [2.5426462],
       [3.1831067],
       [2.7223055],
       [2.2366428],
       [2.5343153],
       [1.8868359],
       [2.2543533],
       [1.6699659],
       [3.5473552],
       [2.0310278],
       [2.1610875],
       [1.5474242],
       [2.8224456],
       [2.5564902],
       [1.8620824],
       [1.7707801],
       [2.8533561],
       [2.6515357],
       [1.9958668],
       [1.9248507],
       [1.567438 ],
       [1.7784561],
       [1.8084826],
       [2.3496592],
       [2.5493958],
       [1.5351354],
       [1.5991951],
       [1.6866133],
       [2.1989336],
       [2.2575328],
       [2.4101558],
       [2.8309085],
       [4.8953133],
       [2.0503767],
       [1.7298037],
       [4.151154 ],
       [2.68068  ],
       [2.2968798],
       [2.4844375],
       [2.8274229],
       [1.4319184],
       [3.0269961],
       [2.9550996],
       [3.343604 ],
       [2.9918175],
       [2.8108432],
       [2.4181383],
       [1.6882929],
       [4.23102  ],
       [2.2197623],
       [3.1626108],
       [1.5306203],
       [2.0423267],
       [1.9552183],
       [1.6401459],
       [1.6042129],
       [2.6679442],
       [2.389199 ],
       [1.5021943],
       [2.610205 ],
       [1.6743946],
       [1.875874 ],
       [3.333657 ],
       [2.5975168],
       [3.582843 ],
       [1.697876 ],
       [3.3963478],
       [2.254197 ],
       [1.7597001],
       [2.1790102],
       [1.5331519],
       [1.9952327],
       [2.3327775],
       [2.3734338],
       [3.2080224],
       [2.3776374],
       [2.244727 ],
       [2.7159064],
       [1.8959639],
       [2.8179734],
       [3.1035154],
       [2.606758 ],
       [2.8360193],
       [2.7399   ],
       [1.6688957],
       [2.4770346],
       [2.2415266],
       [3.0984826],
       [2.1247113],
       [1.6563303],
       [2.525667 ],
       [2.4190247],
       [3.7466018],
       [2.5604758],
       [2.6025069],
       [2.6931865],
       [2.3962328],
       [2.1390767],
       [1.5645984],
       [2.3214276],
       [2.4740045],
       [2.4938383],
       [3.6674275],
       [2.4300857],
       [1.6584629],
       [1.6486264],
       [2.4925425],
       [2.3455446],
       [2.5340507],
       [2.5445848],
       [2.493406 ],
       [2.7297575],
       [2.6729937],
       [1.7758833],
       [2.207224 ],
       [2.2066753],
       [2.4540648],
       [1.7895379],
       [1.7116075],
       [1.8508534],
       [2.449735 ],
       [3.8064635],
       [1.6833897],
       [2.4485643],
       [1.866796 ],
       [1.5908372],
       [3.1976554],
       [2.7753005],
       [2.2584496],
       [1.5670846],
       [2.0656886],
       [2.679134 ],
       [2.2664578],
       [2.7799513],
       [2.148843 ],
       [1.8215381],
       [2.1618955],
       [2.571005 ],
       [2.943077 ],
       [2.3366344],
       [2.7061396],
       [1.9383992],
       [1.6698174],
       [1.8076273],
       [2.134824 ],
       [2.275501 ],
       [2.2525818],
       [1.5757802],
       [1.5341914],
       [2.559285 ],
       [2.7860928],
       [1.8149819],
       [2.1997843],
       [2.5523021],
       [1.9736481],
       [2.700489 ],
       [2.4930255],
       [2.4274182],
       [3.7538385],
       [2.039463 ],
       [1.5566033],
       [2.4109275],
       [2.6354659],
       [2.2537103],
       [2.3201602],
       [2.2721627],
       [3.2056139],
       [2.5096724],
       [2.6651082],
       [2.3558   ],
       [2.9475338],
       [1.9231247],
       [2.289051 ],
       [1.8960205],
       [2.5052855],
       [1.6618557],
       [3.1323063],
       [1.7491242],
       [2.5576785],
       [2.3391683],
       [2.2902944],
       [1.8669962],
       [2.0287209],
       [1.6401256],
       [2.2522066],
       [1.6451457],
       [3.2285316],
       [2.1452816],
       [2.6579335],
       [2.310786 ],
       [2.417743 ],
       [2.839476 ],
       [2.118476 ],
       [4.1560726],
       [2.3361647],
       [2.6438615],
       [3.0608528],
       [3.7604592],
       [2.4393754],
       [1.3564055],
       [1.9380281],
       [2.5188367],
       [1.9058552],
       [2.335706 ],
       [2.3997753],
       [1.7418014],
       [2.4389908],
       [1.8120348],
       [2.4965165],
       [3.1262932],
       [2.960096 ],
       [1.9732752],
       [2.871673 ],
       [2.5424674],
       [2.0276728],
       [2.78145  ],
       [2.1474757],
       [2.0154247],
       [3.3778377],
       [3.179256 ],
       [1.9751725],
       [2.1168137],
       [1.4534659],
       [2.8984718],
       [3.3951514],
       [2.3229532],
       [2.1675127],
       [2.3670866],
       [1.632535 ],
       [2.4571981],
       [1.9446368],
       [3.158672 ],
       [2.549193 ],
       [1.6317449],
       [1.5908486],
       [2.2457092],
       [2.4461963],
       [3.905827 ],
       [1.8816509],
       [2.470602 ],
       [2.6779704],
       [2.683493 ],
       [3.053569 ],
       [2.836799 ],
       [1.9832445],
       [2.089979 ],
       [2.5866525],
       [2.4085476],
       [2.0297232],
       [1.5495951],
       [1.7562265],
       [1.8393211],
       [1.696891 ],
       [1.802467 ],
       [2.3733263],
       [1.7712666],
       [3.8952868],
       [2.467142 ],
       [2.4429882],
       [1.6958468],
       [2.3926122],
       [2.896186 ],
       [2.2798634],
       [2.385541 ],
       [2.3487508],
       [2.9067686],
       [2.8783948],
       [2.0156279],
       [2.598648 ],
       [3.4583347],
       [1.6624725],
       [3.3822591],
       [2.5693166],
       [1.9821618],
       [2.0956447],
       [1.9567546],
       [2.6252856],
       [3.192901 ],
       [1.8534659],
       [3.1816728],
       [2.3711464],
       [2.448264 ],
       [1.544835 ],
       [2.5852535],
       [1.8131974],
       [2.89379  ],
       [2.6367974],
       [2.3335674],
       [1.7633468],
       [2.4901454],
       [2.7156875],
       [2.4581268],
       [3.0443125],
       [2.9668934],
       [1.8738818],
       [2.4078958],
       [2.0522177],
       [1.9557999],
       [2.6378872],
       [2.616893 ],
       [3.4414382],
       [2.6080706],
       [1.5448353],
       [2.582645 ],
       [3.0877821],
       [3.373771 ],
       [2.6414018],
       [2.116813 ],
       [1.794098 ],
       [2.0743706],
       [1.6411822],
       [1.5309952],
       [3.2316072],
       [2.4409373],
       [1.8351364],
       [1.6218935],
       [2.4551857],
       [1.6414261],
       [3.098715 ],
       [2.5716436],
       [2.2044258],
       [2.0890882],
       [3.2109392],
       [3.9159148],
       [3.1552122],
       [2.1156251],
       [2.2525442],
       [2.4959033],
       [2.5729322],
       [3.2276218],
       [1.8635008],
       [2.4835038],
       [3.209979 ],
       [1.6139067],
       [2.322941 ],
       [2.1566703],
       [3.1425054],
       [3.153783 ],
       [2.3846114],
       [2.1019745],
       [1.9047517],
       [2.1214252],
       [2.4238255],
       [3.0795124],
       [2.5914967],
       [2.5696013],
       [1.659911 ],
       [2.165194 ],
       [2.0473268],
       [2.611849 ],
       [3.0249836],
       [2.987638 ],
       [2.8796265],
       [1.9016074],
       [2.8831725],
       [2.911266 ],
       [2.5460417],
       [2.0615878],
       [1.7388043],
       [1.4560542],
       [2.364578 ],
       [2.5710123],
       [2.2005389],
       [1.9533398],
       [2.4496891],
       [2.3221676],
       [2.7527506],
       [2.622667 ],
       [2.3611472],
       [1.9000657],
       [1.5617154],
       [2.7158396],
       [1.883199 ],
       [2.9005406],
       [2.0225978],
       [1.8004103],
       [3.0935035],
       [1.6649073],
       [2.6138775],
       [2.647638 ],
       [1.6627184],
       [3.4305036],
       [2.6199682],
       [2.9713557],
       [2.0901031],
       [2.760673 ],
       [2.7598455],
       [2.5496037],
       [2.4750936],
       [2.9051778],
       [2.7413862],
       [2.5379202],
       [2.3360875],
       [2.1078422],
       [2.4602659],
       [1.8124207],
       [2.3699284],
       [2.507179 ],
       [2.4767463],
       [1.7105888],
       [1.457231 ],
       [4.9003954],
       [2.2735732],
       [2.707506 ],
       [2.3844273],
       [1.7247156],
       [1.7911551],
       [1.9609352],
       [2.1207385],
       [2.6640062],
       [3.1730056],
       [2.0464501],
       [3.3694434],
       [2.0568428],
       [1.8412292],
       [2.5568378],
       [2.5999272],
       [1.8345606],
       [2.4786303],
       [2.3264039],
       [2.8378112],
       [2.4928858],
       [2.3689392],
       [2.5256279],
       [2.9953783],
       [1.5977796],
       [1.5446806],
       [1.6853503],
       [1.5350841],
       [1.7793185],
       [2.1248643],
       [2.6340635],
       [2.0519526],
       [2.3078997],
       [2.157923 ],
       [2.380058 ],
       [1.9836562],
       [2.953971 ],
       [2.3530953],
       [2.1094275],
       [2.1162739],
       [1.4948332],
       [2.2323613],
       [2.2092927],
       [2.7167351],
       [2.3514233],
       [1.4583757],
       [2.810064 ],
       [2.656511 ],
       [3.9274547],
       [3.7235992],
       [2.5817373],
       [3.094917 ],
       [2.3351448],
       [1.6868664],
       [2.6041715],
       [2.3728087],
       [1.6983249],
       [1.6535472],
       [1.6503923],
       [2.483899 ],
       [1.5467744],
       [2.0687878],
       [2.8695147],
       [2.8001387],
       [2.9998717],
       [3.236657 ],
       [2.3818538],
       [1.9987946],
       [2.31168  ],
       [2.1857467],
       [2.6204588],
       [1.5353502],
       [2.296421 ],
       [1.6733266],
       [1.8273921],
       [2.5635378],
       [2.3023832],
       [1.6971291],
       [1.7615558],
       [2.1495438],
       [1.5294889],
       [1.6868585],
       [2.2077918],
       [2.5897813],
       [1.7172928],
       [2.0157652],
       [1.8820837],
       [3.0770779],
       [1.9572403],
       [2.4905598],
       [1.9540724],
       [1.9037519],
       [2.726563 ],
       [3.0295234],
       [2.447872 ],
       [1.8878614],
       [1.574965 ],
       [1.7311742],
       [2.316563 ],
       [2.1037602],
       [1.7548336],
       [2.8129685],
       [2.132792 ],
       [2.4491777],
       [2.8999693],
       [2.250165 ],
       [2.0478747],
       [2.0643902],
       [3.200248 ],
       [1.8868717],
       [2.2213676],
       [2.0291553],
       [2.1312847],
       [1.9700836],
       [2.7739358],
       [1.6798517],
       [1.4837193],
       [1.5092381],
       [1.9000902],
       [2.5573294],
       [3.0865903],
       [2.5530646],
       [2.5338488],
       [2.0439734],
       [2.2028005],
       [1.695357 ],
       [2.4127123],
       [2.5784175],
       [2.7835164],
       [2.0956404],
       [2.8896172],
       [3.5972095],
       [1.5353147],
       [3.3637173],
       [3.7350676],
       [1.4158137],
       [2.0796475],
       [1.5797893],
       [1.8285382],
       [3.2425642],
       [1.8168727],
       [2.5874808],
       [2.406516 ],
       [2.6352255],
       [1.4938507],
       [2.359526 ],
       [2.9967928],
       [2.9959965],
       [2.7549598],
       [1.4973054],
       [1.5046853],
       [3.2588165],
       [2.795373 ],
       [1.8374611],
       [3.5543535],
       [1.4173592],
       [2.1545851],
       [2.9474905],
       [2.8545299],
       [2.3108475],
       [1.856034 ],
       [2.0267434],
       [2.7059495],
       [1.8959676],
       [2.4648845],
       [2.7758064],
       [2.262585 ],
       [2.4933608],
       [3.7336268],
       [2.5002878],
       [2.3236938],
       [1.6736462],
       [1.8163906],
       [2.2631433],
       [2.7074077],
       [2.8541396],
       [1.613517 ],
       [2.0323894],
       [2.3641012],
       [1.9049658],
       [2.4358754],
       [2.4808848],
       [2.113677 ],
       [1.7824727],
       [2.4979143],
       [2.0831466],
       [3.1212187],
       [1.9727231],
       [2.5077255],
       [2.7290533],
       [2.6537614],
       [1.9351165],
       [1.9959565],
       [3.2797406],
       [2.074681 ],
       [2.224599 ],
       [2.4102075],
       [1.7481123],
       [1.8432046],
       [2.2797148],
       [2.7183874],
       [1.9029062],
       [1.7574275],
       [2.3009295],
       [1.4316454],
       [3.4814527],
       [1.7742863],
       [2.2280042],
       [1.6538312]], dtype=float32)

In [16]:
X_test

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 05 Air Flow,Flotation Column 06 Air Flow,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level
1299,0.924045,0.154254,0.368949,0.248496,0.602513,0.352474,0.376264,0.543453,0.549127,0.580123,...,0.643113,0.655122,0.660716,0.476501,0.462262,0.203086,0.371669,0.296854,0.294054,0.348649
1338,0.924045,0.154254,0.474367,0.602007,0.561336,0.469464,0.680680,0.543521,0.546747,0.579769,...,0.659766,0.652421,0.660063,0.396192,0.372293,0.352494,0.365601,0.297068,0.301979,0.348932
3875,0.514323,0.514179,0.831941,0.828291,0.613499,0.300370,0.564498,0.908511,0.922720,0.977790,...,0.632451,0.965161,0.718463,0.617867,0.621220,0.620636,0.386211,0.299516,0.597400,0.356348
2083,0.574219,0.342786,0.242883,0.394767,0.553913,0.226068,0.118023,0.909200,0.925393,0.977180,...,0.658170,0.652666,0.662469,0.322359,0.292956,0.353020,0.565346,0.512588,0.801465,0.880956
1498,0.924045,0.154254,0.263906,0.000894,0.065159,0.268613,0.007165,0.896438,0.486064,0.922628,...,0.608764,0.201692,0.541185,0.969783,0.005072,0.962663,0.829858,0.887452,0.930749,0.280885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,0.924045,0.154254,0.577762,0.253142,0.559007,0.605770,0.390407,0.908501,0.545203,0.976398,...,0.646900,0.650832,0.660217,0.616541,0.622153,0.620176,0.658323,0.623334,0.600224,0.668818
3812,0.576389,0.380181,0.450600,0.581032,0.130932,0.017853,0.509852,0.906918,0.925973,0.976910,...,0.652459,0.652452,0.658220,0.612930,0.619070,0.354424,0.301861,0.294544,0.498446,0.347375
2629,0.554253,0.452477,0.660020,0.593917,0.526973,0.789152,0.521162,0.908808,0.924183,0.977182,...,0.653845,0.651002,0.661643,0.616946,0.620319,0.620013,0.653692,0.619577,0.498111,0.562652
1427,0.924045,0.154254,0.355122,0.238457,0.552648,0.553403,0.033398,0.908385,0.923754,0.977532,...,0.637441,0.652442,0.661256,0.598630,0.490933,0.707704,0.306811,0.291255,0.296135,0.335803
67,0.707899,0.308196,0.670966,0.143318,0.604406,0.595002,1.000000,0.544784,0.547378,0.580419,...,0.969443,0.340244,0.331630,0.940428,0.945337,0.967640,0.758561,0.756022,0.793059,0.806454

In [17]:
df

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 06 Air Flow,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.20,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,251.232529,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,1.31
2017-03-10 02:00:00,55.20,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.909494,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,1.11
2017-03-10 03:00:00,55.20,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.242161,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,1.27
2017-03-10 04:00:00,55.20,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,249.825122,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,1.36
2017-03-10 05:00:00,55.20,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.249600,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-09 19:00:00,49.75,23.20,3327.047776,497.211189,380.847200,9.176166,1.660871,301.565561,300.169133,299.900722,...,335.658144,298.736661,397.781583,498.753311,403.858956,398.930467,502.971728,399.468911,400.559511,1.65
2017-09-09 20:00:00,49.75,23.20,4225.800333,508.963856,381.112889,9.387541,1.691996,300.050172,299.967839,299.906550,...,348.172800,303.599269,399.928567,499.648950,399.208611,399.967122,501.624533,398.905006,400.486233,1.71
2017-09-09 21:00:00,49.75,23.20,2808.214692,517.748822,381.064411,9.771277,1.735647,299.814289,299.801561,299.973161,...,349.422803,309.875439,399.961433,500.484917,471.827489,399.931033,500.223311,401.899806,400.556333,1.80
2017-09-09 22:00:00,49.75,23.20,3191.497672,492.511228,380.445006,9.782121,1.716644,300.122756,299.679472,299.927028,...,349.613589,305.254558,399.601383,498.614494,836.277192,400.455389,500.406239,402.703283,401.769072,1.96
2017-09-09 23:00:00,49.75,23.20,3638.543653,460.769950,380.823147,9.653802,1.667825,299.778889,300.095394,299.840833,...,349.355083,315.264733,400.026289,499.721794,868.549247,398.764744,500.682167,399.375644,398.775261,1.71