In [1]:
import numpy as np

import pandas as pd

import tensorflow as tf 

import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv('MiningProcess_Flotation_Plant_Database_hour.csv')
df.set_index('date', inplace=True)

In [3]:
df.head()

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,p-Flotation Column 01 Air Flow,p-Flotation Column 02 Air Flow,p-Flotation Column 03 Air Flow,...,p-Flotation Column 07 Air Flow,p-Flotation Column 01 Level,p-Flotation Column 02 Level,p-Flotation Column 03 Level,p-Flotation Column 04 Level,p-Flotation Column 05 Level,p-Flotation Column 06 Level,p-Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.2,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,66.91,1.31
2017-03-10 02:00:00,55.2,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,67.06,1.11
2017-03-10 03:00:00,55.2,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,66.97,1.27
2017-03-10 04:00:00,55.2,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,66.75,1.36
2017-03-10 05:00:00,55.2,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,66.63,1.34

In [4]:

df = df.drop(['% Iron Concentrate'], axis=1)

In [5]:
Y = df['% Silica Concentrate']
X = df.drop(['% Silica Concentrate'], axis=1)

In [6]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scaled = pd.DataFrame(min_max_scaler.fit_transform(X), columns=X.columns)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [8]:
df.head()

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,p-Flotation Column 01 Air Flow,p-Flotation Column 02 Air Flow,p-Flotation Column 03 Air Flow,...,p-Flotation Column 06 Air Flow,p-Flotation Column 07 Air Flow,p-Flotation Column 01 Level,p-Flotation Column 02 Level,p-Flotation Column 03 Level,p-Flotation Column 04 Level,p-Flotation Column 05 Level,p-Flotation Column 06 Level,p-Flotation Column 07 Level,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.2,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,251.232529,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,1.31
2017-03-10 02:00:00,55.2,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.909494,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,1.11
2017-03-10 03:00:00,55.2,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.242161,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,1.27
2017-03-10 04:00:00,55.2,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,249.825122,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,1.36
2017-03-10 05:00:00,55.2,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.249600,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,1.34

In [9]:

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 
from math import sqrt  


n_features = X_train.shape[1]

# define model
model = Sequential()
model.add(Dense(21,activation='relu', kernel_initializer='he_normal', input_shape=(n_features,)))
model.add(Dense(8,activation='relu',  kernel_initializer='he_normal'))
model.add(Dense(1))

# compile the model
model.compile(optimizer='adam', loss='mse')

In [10]:
model.fit(X_train, Y_train, epochs=50, batch_size=32, verbose=1)

Epoch 1/50
103/103 [==============================] - 0s 3ms/step - loss: 2.2484
Epoch 2/50
103/103 [==============================] - 0s 3ms/step - loss: 1.2785
Epoch 3/50
103/103 [==============================] - 0s 3ms/step - loss: 1.1926
Epoch 4/50
103/103 [==============================] - 0s 3ms/step - loss: 1.1379
Epoch 5/50
103/103 [==============================] - 0s 3ms/step - loss: 1.1086
Epoch 6/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0864
Epoch 7/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0735
Epoch 8/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0683
Epoch 9/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0580
Epoch 10/50
103/103 [==============================] - 0s 4ms/step - loss: 1.0529
Epoch 11/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0453
Epoch 12/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0503
Epoch 13/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0375
Epoch 14/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0275
Epoch 15/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0262
Epoch 16/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0295
Epoch 17/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0275A: 0s - loss: 0
Epoch 18/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0245
Epoch 19/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0121
Epoch 20/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0163
Epoch 21/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0068
Epoch 22/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0117
Epoch 23/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0209
Epoch 24/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0072A: 0s - loss: 0
Epoch 25/50
103/103 [==============================] - 0s 3ms/step - loss: 1.0055
Epoch 26/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9934
Epoch 27/50
103/103 [==============================] - 0s 2ms/step - loss: 1.0006
Epoch 28/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9934
Epoch 29/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9984
Epoch 30/50
103/103 [==============================] - 0s 2ms/step - loss: 1.0002
Epoch 31/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9914
Epoch 32/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9859
Epoch 33/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9862
Epoch 34/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9890
Epoch 35/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9863
Epoch 36/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9759
Epoch 37/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9774
Epoch 38/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9848
Epoch 39/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9777
Epoch 40/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9784
Epoch 41/50
103/103 [==============================] - 0s 3ms/step - loss: 0.9688
Epoch 42/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9677
Epoch 43/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9745
Epoch 44/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9720
Epoch 45/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9649
Epoch 46/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9692
Epoch 47/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9550
Epoch 48/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9732
Epoch 49/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9618
Epoch 50/50
103/103 [==============================] - 0s 2ms/step - loss: 0.9662

In [11]:
error = model.evaluate(X_test, Y_test)
print('MSE: %.3f, RMSE: %.3f' % (error, sqrt(error)))

26/26 [==============================] - 0s 2ms/step - loss: 1.0377
MSE: 1.038, RMSE: 1.019

In [12]:
i = 1299
row = [df['% Iron Feed'].iloc[i],df['% Silica Feed'].iloc[i],df['Starch Flow'].iloc[i],df['Amina Flow'].iloc[i],df['Ore Pulp Flow'].iloc[i],df['Ore Pulp pH'].iloc[i],df['Ore Pulp Density'].iloc[i],df['Flotation Column 01 Air Flow'].iloc[i],df['Flotation Column 02 Air Flow'].iloc[i],df['Flotation Column 03 Air Flow'].iloc[i],df['Flotation Column 04 Air Flow'].iloc[i],df['Flotation Column 05 Air Flow'].iloc[i],df['Flotation Column 06 Air Flow'].iloc[i],df['Flotation Column 07 Air Flow'].iloc[i],df['Flotation Column 01 Level'].iloc[i],df['Flotation Column 02 Level'].iloc[i],df['Flotation Column 03 Level'].iloc[i],df['Flotation Column 04 Level'].iloc[i],df['Flotation Column 05 Level'].iloc[i],df['Flotation Column 06 Level'].iloc[i],df['Flotation Column 07 Level'].iloc[i]]
row = min_max_scaler.transform([row])
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

KeyError: 'Flotation Column 01 Air Flow'

In [ ]:
row

In [ ]:
yhatt = model.predict(X_test)
yhatt

In [16]:
X_test

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 05 Air Flow,Flotation Column 06 Air Flow,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level
1299,0.924045,0.154254,0.368949,0.248496,0.602513,0.352474,0.376264,0.543453,0.549127,0.580123,...,0.643113,0.655122,0.660716,0.476501,0.462262,0.203086,0.371669,0.296854,0.294054,0.348649
1338,0.924045,0.154254,0.474367,0.602007,0.561336,0.469464,0.680680,0.543521,0.546747,0.579769,...,0.659766,0.652421,0.660063,0.396192,0.372293,0.352494,0.365601,0.297068,0.301979,0.348932
3875,0.514323,0.514179,0.831941,0.828291,0.613499,0.300370,0.564498,0.908511,0.922720,0.977790,...,0.632451,0.965161,0.718463,0.617867,0.621220,0.620636,0.386211,0.299516,0.597400,0.356348
2083,0.574219,0.342786,0.242883,0.394767,0.553913,0.226068,0.118023,0.909200,0.925393,0.977180,...,0.658170,0.652666,0.662469,0.322359,0.292956,0.353020,0.565346,0.512588,0.801465,0.880956
1498,0.924045,0.154254,0.263906,0.000894,0.065159,0.268613,0.007165,0.896438,0.486064,0.922628,...,0.608764,0.201692,0.541185,0.969783,0.005072,0.962663,0.829858,0.887452,0.930749,0.280885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,0.924045,0.154254,0.577762,0.253142,0.559007,0.605770,0.390407,0.908501,0.545203,0.976398,...,0.646900,0.650832,0.660217,0.616541,0.622153,0.620176,0.658323,0.623334,0.600224,0.668818
3812,0.576389,0.380181,0.450600,0.581032,0.130932,0.017853,0.509852,0.906918,0.925973,0.976910,...,0.652459,0.652452,0.658220,0.612930,0.619070,0.354424,0.301861,0.294544,0.498446,0.347375
2629,0.554253,0.452477,0.660020,0.593917,0.526973,0.789152,0.521162,0.908808,0.924183,0.977182,...,0.653845,0.651002,0.661643,0.616946,0.620319,0.620013,0.653692,0.619577,0.498111,0.562652
1427,0.924045,0.154254,0.355122,0.238457,0.552648,0.553403,0.033398,0.908385,0.923754,0.977532,...,0.637441,0.652442,0.661256,0.598630,0.490933,0.707704,0.306811,0.291255,0.296135,0.335803
67,0.707899,0.308196,0.670966,0.143318,0.604406,0.595002,1.000000,0.544784,0.547378,0.580419,...,0.969443,0.340244,0.331630,0.940428,0.945337,0.967640,0.758561,0.756022,0.793059,0.806454

In [17]:
df

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,Flotation Column 03 Air Flow,...,Flotation Column 06 Air Flow,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Silica Concentrate
date,,,,,,,,,,,,,,,,,,,,,
2017-03-10 01:00:00,55.20,16.98,3162.625026,578.786678,398.753368,10.113487,1.729558,251.166672,250.226086,250.178287,...,251.232529,250.208184,450.383776,446.891845,450.474523,449.912259,455.792161,464.383310,450.532747,1.31
2017-03-10 02:00:00,55.20,16.98,3133.256389,537.219661,399.871822,10.129742,1.667784,249.880589,250.214050,250.033317,...,249.909494,249.897572,449.373361,450.249356,450.081222,450.328806,448.722983,455.501528,451.387700,1.11
2017-03-10 03:00:00,55.20,16.98,3479.482944,591.906744,398.763806,10.048403,1.732711,250.161328,250.104167,250.046350,...,250.242161,250.484183,449.972878,450.868711,450.901822,451.145822,451.134189,459.981311,450.296722,1.27
2017-03-10 04:00:00,55.20,16.98,3228.036436,593.170106,399.866983,9.918614,1.731056,250.208772,250.204761,250.120861,...,249.825122,250.157622,487.940706,491.462111,487.387206,494.528183,495.664011,502.763850,494.939889,1.36
2017-03-10 05:00:00,55.20,16.98,3327.280739,619.710806,399.615089,9.746029,1.765879,249.917800,250.160494,250.013500,...,250.249600,250.078639,549.031539,549.983156,549.459572,549.975483,549.512533,560.696300,550.271772,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-09 19:00:00,49.75,23.20,3327.047776,497.211189,380.847200,9.176166,1.660871,301.565561,300.169133,299.900722,...,335.658144,298.736661,397.781583,498.753311,403.858956,398.930467,502.971728,399.468911,400.559511,1.65
2017-09-09 20:00:00,49.75,23.20,4225.800333,508.963856,381.112889,9.387541,1.691996,300.050172,299.967839,299.906550,...,348.172800,303.599269,399.928567,499.648950,399.208611,399.967122,501.624533,398.905006,400.486233,1.71
2017-09-09 21:00:00,49.75,23.20,2808.214692,517.748822,381.064411,9.771277,1.735647,299.814289,299.801561,299.973161,...,349.422803,309.875439,399.961433,500.484917,471.827489,399.931033,500.223311,401.899806,400.556333,1.80
2017-09-09 22:00:00,49.75,23.20,3191.497672,492.511228,380.445006,9.782121,1.716644,300.122756,299.679472,299.927028,...,349.613589,305.254558,399.601383,498.614494,836.277192,400.455389,500.406239,402.703283,401.769072,1.96
2017-09-09 23:00:00,49.75,23.20,3638.543653,460.769950,380.823147,9.653802,1.667825,299.778889,300.095394,299.840833,...,349.355083,315.264733,400.026289,499.721794,868.549247,398.764744,500.682167,399.375644,398.775261,1.71